---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[app-sampleapp::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: git
    run_list:
      - recipe[app-sampleapp::git]
    verifier:
      inspec_tests:
        - test/smoke/git
    attributes:
  - name: postgres
    run_list:
      - recipe[app-sampleapp::postgres]
    verifier:
      inspec_tests:
        - test/smoke/postgres
    attributes:
      postgresql:
        password:
          postgres: supersecret
